-- Add up migration script here
CREATE TABLE gambling_mine(
    id BIGINT PRIMARY KEY,
    miners BIGINT NOT NULL DEFAULT 0,
    mines BIGINT NOT NULL DEFAULT 0,
    land BIGINT NOT NULL DEFAULT 0,
    countries BIGINT NOT NULL DEFAULT 0,
    continents BIGINT NOT NULL DEFAULT 0,
    planets BIGINT NOT NULL DEFAULT 0,
    solar_systems BIGINT NOT NULL DEFAULT 0,
    galaxies BIGINT NOT NULL DEFAULT 0,
    universes BIGINT NOT NULL DEFAULT 0,
    prestige BIGINT NOT NULL DEFAULT 0,
    coal BIGINT NOT NULL DEFAULT 0,
    iron BIGINT NOT NULL DEFAULT 0,
    gold BIGINT NOT NULL DEFAULT 0,
    redstone BIGINT NOT NULL DEFAULT 0,
    lapis BIGINT NOT NULL DEFAULT 0,
    diamonds BIGINT NOT NULL DEFAULT 0,
    emeralds BIGINT NOT NULL DEFAULT 0,
    tech BIGINT NOT NULL DEFAULT 0,
    utility BIGINT NOT NULL DEFAULT 0,
    production BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT gambling
        FOREIGN KEY (id)
        REFERENCES gambling (id)
);